spec:
  app:
    metadata:
      name: sfgw-job
      repository: sf-gateway
      env: production
      component: job-server
    projectID: dom-sfgw-prod-7a42
    clusterProjectID: dom-cie-prod-de83
    clusterLocation: asia-south1
    clusterName: dom-cie-prod-gke-cluster
    serviceAccount:
      gcpServiceAccount: sfgw-app
      name: sf-gateway-job
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      automount: true
    configMap:
      - name: sfgw-job-application-configs
        mountPath: /home/app/configuration/properties
        filePaths:
          - values/common/dom/prod/configs/*
          - values/sqs/dom/prod/configs/*
      - name: sfgw-job-application-flyway-configs
        annotations:
          argocd.argoproj.io/sync-wave: "-2"
        filePaths:
          - values/common/dom/migrations
    externalSecrets:
      - name: sfgw-job-secrets
        mountPath: /home/app/configuration/secrets
        data:
          - secretKey: salesforce_secrets.properties
            remoteRefKey: salesforce-secrets-properties
          - secretKey: psql_secrets.properties
            remoteRefKey: psql-secrets-properties-job
          - secretKey: flyway.conf
            remoteRefKey: flyway-config-secrets
          - secretKey: application_secrets.properties
            remoteRefKey: application-secrets-properties
    jobs:
      - name: sfgw-job-flyway-migrate
        containers:
          name: flyway-migrations
          image: flyway/flyway
          resources:
            limits:
              cpu: 2560m
              memory: 2048Mi
            requests:
              cpu: 256m
              memory: 1024Mi
          args: [ "migrate" ]
        volumes:
          - name: flyway-job-migrations
            mountPath: /flyway/sql
            configMap:
              name: sfgw-job-application-flyway-configs
          - name: sfgw-job-secrets-volume
            mountPath: /flyway/conf
            secret:
              secretName: sfgw-job-secrets
    deployment:
      replicas: 2
      containers:
        - name: sfgw-job
          image:
            registry: dom-dpq-prod-3143/dom-dpq-prod-sf-gateway-application/job
          envFile: values/sqs/dom/prod/env.yaml
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2560m
              memory: 2048Mi
            requests:
              cpu: 256m
              memory: 1024Mi
          probe:
            default:
              type:
                exec:
                  command:
                    - /bin/true
            startup:
              type:
                exec:
                  command:
                    - /bin/true
              parameters:
                initialDelaySeconds: 60
                periodSeconds: 30
    rollout:
      enabled: true
      job_subscription_ids:
      - "dom-sfgw-prod-topic-jobs-subscription"
    horizontalPodAutoScaler:
      minReplicas: 2
      maxReplicas: 8
      metadata:
        labels: {}
      metrics:
        - type: resource
          name: cpu
          value: 70.0
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 180
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 180
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
